--------------------------------------------------------
--  DDL for Materialized View MV_MTR_SRD_METERING_STG
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "ASB_STG"."MV_MTR_SRD_METERING_STG" ("LOAD_SEQ_NBR", "ASB_UNIT_CODE", "CONTRACT_NUMBER", "EFFECTIVE", "REC_LEVEL", "FILE_DATE", "MSRMT_DTTM", "DATE_CREATED", "EFF_MTR_DELAY", "METER_DELAY")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH FORCE ON DEMAND
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE QUERY REWRITE
  AS select s.*,
        s.effective + NVL(ms.meter_delay,0)/1440 as EFF_MTR_DELAY,
        NVL(ms.meter_delay,0) AS METER_DELAY
            from SRD_METERING_STG s LEFT OUTER JOIN mv_mtr_srs_monitoring ms
            ON (s.ASB_UNIT_CODE = ms.ASB_UNIT_CODE
            AND s.effective >= ms.effective 
            AND s.effective < ms.effective_end);

   COMMENT ON MATERIALIZED VIEW "ASB_STG"."MV_MTR_SRD_METERING_STG"  IS 'snapshot table for snapshot ASB_STG.MV_MTR_SRD_METERING_STG';
