--------------------------------------------------------
--  DDL for Materialized View MV_MTR_SRS_MONITORING
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "ASB_STG"."MV_MTR_SRS_MONITORING" ("ASB_UNIT_CODE", "METER_DELAY", "EFFECTIVE", "EFFECTIVE_END")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH FORCE ON DEMAND
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE QUERY REWRITE
  AS SELECT asb_unit_code, meter_delay, effective, 
            LEAD(effective,1,SYSDATE) OVER( PARTITION BY asb_unit_code ORDER BY asb_unit_code, effective) AS effective_end
            FROM SRS_MONITORING_STG;

   COMMENT ON MATERIALIZED VIEW "ASB_STG"."MV_MTR_SRS_MONITORING"  IS 'snapshot table for snapshot ASB_STG.MV_MTR_SRS_MONITORING';
  