--------------------------------------------------------
--  DDL for Procedure PR_CONTRACT_STAGING_TRANS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "ASB_STG"."PR_CONTRACT_STAGING_TRANS" 
/**************************************************************************************
*
* Program Name           :PR_CONTRACT_STAGING_TRANS
* Author                 :IBM(Shailesh Solanki)
* Creation Date          :03-05-2021
* Description            :This is a PL/SQL procedure. This procedure transfer contract data
*                         from MSM_STG2 to C2M system
*
* Calling Program        :None
* Called Program         :PR_ASB_LOAD_CONTRACT_MAIN
*
*
* Input files            :None
* Output files           :None
* Input Parameter        :csv file receive status
* Output Parameter       :None
* Modifications  History :None
*
* <DD-MM-YYYY>   <Modifier Name>    <Description>
*
**************************************************************************************/
(pi_load_seq_nbr IN NUMBER) AS
BEGIN
    --CI_SA TABLE
    --DELETE FROM CI_SA@STG_MSM_LINK;
    INSERT INTO CI_SA@STG_MSM_LINK
    SELECT SA_ID,PROP_DCL_RSN_CD,PROP_SA_ID,CIS_DIVISION,SA_TYPE_CD,START_OPT_CD,START_DT,SA_STATUS_FLG,ACCT_ID,END_DT,OLD_ACCT_ID ,CUST_READ_FLG,ALLOW_EST_SW,SIC_CD,CHAR_PREM_ID,TOT_TO_BILL_AMT,
    CURRENCY_CD,VERSION,SA_REL_ID,STRT_RSN_FLG,STOP_RSN_FLG,STRT_REQED_BY,STOP_REQED_BY,HIGH_BILL_AMT,INT_CALC_DT,CIAC_REVIEW_DT,BUS_ACTIVITY_DESC,IB_SA_CUTOFF_TM,IB_BASE_TM_DAY_FLG,ENRL_ID,
    SPECIAL_USAGE_FLG,PROP_SA_STAT_FLG ,NBR_PYMNT_PERIODS,NB_RULE_CD,EXPIRE_DT,RENEWAL_DT,NB_APAY_FLG,SA_DATA_AREA FROM MSM_STG2.CI_SA ;
    --PR_DATA_MIGRATION_COUNT(pi_load_seq_nbr,'PR_CONTRACT_STAGING_TRANS','CI_SA');

    --CI_SA_SP TABLE
    --DELETE FROM CI_SA_SP@STG_MSM_LINK;
    INSERT INTO CI_SA_SP@STG_MSM_LINK
    SELECT SP_ID,SA_SP_ID,SA_ID,START_DTTM,START_MR_ID,STOP_DTTM,USAGE_FLG,STOP_MR_ID,VERSION,USE_PCT FROM MSM_STG2.CI_SA_SP ;
   -- PR_DATA_MIGRATION_COUNT(pi_load_seq_nbr,'PR_CONTRACT_STAGING_TRANS','CI_SA_SP');

    --CI_SA_SP_CHAR TABLE
    --DELETE FROM CI_SA_SP_CHAR@STG_MSM_LINK;
    INSERT INTO CI_SA_SP_CHAR@STG_MSM_LINK
    SELECT SA_SP_ID,CHAR_TYPE_CD,EFFDT,CHAR_VAL,VERSION,ADHOC_CHAR_VAL,CHAR_VAL_FK1,CHAR_VAL_FK2,CHAR_VAL_FK3,CHAR_VAL_FK4,CHAR_VAL_FK5 FROM MSM_STG2.CI_SA_SP_CHAR ;
    --PR_DATA_MIGRATION_COUNT(pi_load_seq_nbr,'PR_CONTRACT_STAGING_TRANS','CI_SA_SP_CHAR');

    --D1_US TABLE
    --DELETE FROM D1_US@STG_MSM_LINK;
    INSERT INTO D1_US@STG_MSM_LINK
    SELECT US_ID,BUS_OBJ_CD,BO_STATUS_CD,BO_STATUS_REASON_CD,US_TYPE_CD,D1_SPR_CD,USG_APPR_REQ_FLG,START_DTTM,END_DTTM,CRE_DTTM,STATUS_UPD_DTTM,VERSION,US_STAT_COND_FLG,TIME_ZONE_CD,BO_DATA_AREA ,
    D1_BILL_CYC_CD,US_MP_ID,MOST_RECENT_TRANS_DTTM,DIVISION_CD,ACCESS_GRP_CD FROM MSM_STG2.D1_US;
    --PR_DATA_MIGRATION_COUNT(pi_load_seq_nbr,'PR_CONTRACT_STAGING_TRANS','D1_US');

    --D1_US_CHAR TABLE
    --DELETE FROM D1_US_CHAR@STG_MSM_LINK;
    INSERT INTO D1_US_CHAR@STG_MSM_LINK
    SELECT US_ID,CHAR_TYPE_CD,EFFDT,CHAR_VAL,ADHOC_CHAR_VAL,CHAR_VAL_FK1,CHAR_VAL_FK2,CHAR_VAL_FK3,CHAR_VAL_FK4,CHAR_VAL_FK5,SRCH_CHAR_VAL,VERSION FROM MSM_STG2.D1_US_CHAR;
    --PR_DATA_MIGRATION_COUNT(pi_load_seq_nbr,'PR_CONTRACT_STAGING_TRANS','D1_US_CHAR');

    --D1_US_IDENTIFIER TABLE
    --DELETE FROM D1_US_IDENTIFIER@STG_MSM_LINK;
    INSERT INTO D1_US_IDENTIFIER@STG_MSM_LINK
    SELECT US_ID,US_ID_TYPE_FLG,ID_VALUE,VERSION FROM MSM_STG2.D1_US_IDENTIFIER ;
    --PR_DATA_MIGRATION_COUNT(pi_load_seq_nbr,'PR_CONTRACT_STAGING_TRANS','D1_US_IDENTIFIER');

   --D1_US_FACTOR_OVRD TABLE
    --DELETE FROM D1_US_FACTOR_OVRD@STG_MSM_LINK;
    INSERT INTO D1_US_FACTOR_OVRD@STG_MSM_LINK
    SELECT US_ID,FACTOR_CD,START_DTTM,END_DTTM,VALUE,VERSION FROM MSM_STG2.D1_US_FACTOR_OVRD ;
    --PR_DATA_MIGRATION_COUNT(pi_load_seq_nbr,'PR_CONTRACT_STAGING_TRANS','D1_US_FACTOR_OVRD');

   --D1_US_SP TABLE
    --DELETE FROM D1_US_SP@STG_MSM_LINK;
    INSERT INTO D1_US_SP@STG_MSM_LINK
    SELECT US_ID,D1_SP_ID,START_DTTM,D1_STOP_DTTM,D1_USAGE_FLG,USE_PERCENT,VERSION,BO_DATA_AREA,OVRD_START_DTTM,OVRD_STOP_DTTM FROM MSM_STG2.D1_US_SP ;
    --PR_DATA_MIGRATION_COUNT(pi_load_seq_nbr,'PR_CONTRACT_STAGING_TRANS','D1_US_SP');

     --D1_US_SP_CHAR
    --DELETE FROM D1_US_SP_CHAR@STG_MSM_LINK;
    INSERT INTO D1_US_SP_CHAR@STG_MSM_LINK
    SELECT US_ID,D1_SP_ID,START_DTTM,EFFDT,CHAR_TYPE_CD,CHAR_VAL,ADHOC_CHAR_VAL,CHAR_VAL_FK1,CHAR_VAL_FK2,CHAR_VAL_FK3,CHAR_VAL_FK4,CHAR_VAL_FK5,SRCH_CHAR_VAL,VERSION FROM MSM_STG2.D1_US_SP_CHAR;

    --D1_US_LOG TABLE
    --DELETE FROM D1_US_LOG@STG_MSM_LINK;
    INSERT INTO D1_US_LOG@STG_MSM_LINK
  SELECT US_ID,SEQNO,LOG_DTTM,LOG_ENTRY_TYPE_FLG,DESCRLONG,BO_STATUS_CD,BO_STATUS_REASON_CD,MESSAGE_CAT_NBR,MESSAGE_NBR,CHAR_TYPE_CD,CHAR_VAL,ADHOC_CHAR_VAL,CHAR_VAL_FK1,CHAR_VAL_FK2,CHAR_VAL_FK3,CHAR_VAL_FK4,CHAR_VAL_FK5,USER_ID,VERSION FROM MSM_STG2.D1_US_LOG;


   --D1_US_LOG_PARM TABLE
    --DELETE FROM D1_US_LOG_PARM@STG_MSM_LINK;
    INSERT INTO D1_US_LOG_PARM@STG_MSM_LINK
    SELECT US_ID,SEQNO,PARM_SEQ,MSG_PARM_VAL,MSG_PARM_TYP_FLG,VERSION FROM MSM_STG2.D1_US_LOG_PARM ;
    PR_DATA_MIGRATION_COUNT(pi_load_seq_nbr,'PR_CONTRACT_STAGING_TRANS','D1_US_LOG_PARM');

   --D1_US_QTY TABLE
    --DELETE FROM D1_US_QTY@STG_MSM_LINK;
    INSERT INTO D1_US_QTY@STG_MSM_LINK
    SELECT D1_US_QTY_ID,US_ID,D1_US_QTY_TYPE_CD,START_DTTM,END_DTTM,US_QTY_USG_FLG,BUS_OBJ_CD,
  BO_STATUS_CD,STATUS_UPD_DTTM,CRE_DTTM,'',VERSION,D1_QUANTITY1,D1_QUANTITY2,D1_QUANTITY3,D1_QUANTITY4,
  D1_QUANTITY5 FROM MSM_STG2.D1_US_QTY ;
   -- PR_DATA_MIGRATION_COUNT(pi_load_seq_nbr,'PR_CONTRACT_STAGING_TRANS','D1_US_QTY');

   --D1_US_QTY_LOG TABLE
    --DELETE FROM D1_US_QTY_LOG@STG_MSM_LINK;
    INSERT INTO D1_US_QTY_LOG@STG_MSM_LINK
    SELECT D1_US_QTY_ID,SEQNO,LOG_DTTM,LOG_ENTRY_TYPE_FLG,DESCRLONG,BO_STATUS_CD,BO_STATUS_REASON_CD,
  MESSAGE_CAT_NBR,MESSAGE_NBR,CHAR_TYPE_CD,CHAR_VAL,ADHOC_CHAR_VAL,CHAR_VAL_FK1,CHAR_VAL_FK2,CHAR_VAL_FK3,
  CHAR_VAL_FK4,CHAR_VAL_FK5,USER_ID,VERSION FROM MSM_STG2.D1_US_QTY_LOG ;
    --PR_DATA_MIGRATION_COUNT(pi_load_seq_nbr,'PR_CONTRACT_STAGING_TRANS','D1_US_QTY_LOG');

   ASB_STG.PR_PROCESS_LOG('PR_CONTRACT_STAGING_TRANS',pi_load_seq_nbr,'SUCCESS','Latest data transfer successful from STG2 to MSMS Staging');
EXCEPTION WHEN NO_DATA_FOUND THEN
    ASB_STG.PR_PROCESS_LOG('PR_CONTRACT_STAGING_TRANS',pi_load_seq_nbr,'SUCCESS','No new data found to transfer for sequence number '||pi_load_seq_nbr);
WHEN OTHERS THEN
  ASB_STG.PR_PROCESS_LOG('PR_CONTRACT_STAGING_TRANS',pi_load_seq_nbr,'Failed',SQLERRM);

END PR_CONTRACT_STAGING_TRANS;

/
