--------------------------------------------------------
--  DDL for Index ID_SRD_METERING_STG
--------------------------------------------------------

  CREATE INDEX "ASB_STG"."ID_SRD_METERING_STG" ON "ASB_STG"."SRD_METERING_STG" ("LOAD_SEQ_NBR", "ASB_UNIT_CODE", "CONTRACT_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
