--------------------------------------------------------
--  DDL for Index IDX_ACS_CONT_SEQ
--------------------------------------------------------

  CREATE INDEX "ASB_STG"."IDX_ACS_CONT_SEQ" ON "ASB_STG"."ASB_CONTRACT_SERVICE_STG" ("CONTRACT_SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
