--------------------------------------------------------
--  DDL for Index L_D1_INSTALL_EVT_IDX1
--------------------------------------------------------

  CREATE INDEX "ASB_STG"."L_D1_INSTALL_EVT_IDX1" ON "ASB_STG"."L_D1_INSTALL_EVT" ("D1_SP_ID", "DEVICE_CONFIG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
