--------------------------------------------------------
--  DDL for Index PN_OPERATION_STG2_IX1
--------------------------------------------------------

  CREATE INDEX "ASB_STG"."PN_OPERATION_STG2_IX1" ON "ASB_STG"."PN_OPERATION_STG2" ("EFFECTIVE", "ASB_UNIT_CODE", "RANK") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
