--------------------------------------------------------
--  DDL for Index SRS_FAILURE_PALL_IDX
--------------------------------------------------------

  CREATE INDEX "ASB_STG"."SRS_FAILURE_PALL_IDX" ON "MSM_STG2"."SRS_FAILURE_PALL" ("RESOURCE_CODE", "FAIL_CODE", "FAIL_START", "FAIL_END") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
