--------------------------------------------------------
--  Constraints for Table D1_DYN_OPT_EVENT_06072022
--------------------------------------------------------

  ALTER TABLE "ASB_STG"."D1_DYN_OPT_EVENT_06072022" MODIFY ("VERSION" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."D1_DYN_OPT_EVENT_06072022" MODIFY ("START_DTTM" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."D1_DYN_OPT_EVENT_06072022" MODIFY ("DYN_OPT_ID" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."D1_DYN_OPT_EVENT_06072022" MODIFY ("BO_STATUS_REASON_CD" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."D1_DYN_OPT_EVENT_06072022" MODIFY ("BO_STATUS_CD" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."D1_DYN_OPT_EVENT_06072022" MODIFY ("BUS_OBJ_CD" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."D1_DYN_OPT_EVENT_06072022" MODIFY ("DYN_OPT_EVENT_ID" NOT NULL ENABLE);
