--------------------------------------------------------
--  Constraints for Table D1_DYN_OPT_EVENT_CHAR_06072022
--------------------------------------------------------

  ALTER TABLE "ASB_STG"."D1_DYN_OPT_EVENT_CHAR_06072022" MODIFY ("VERSION" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."D1_DYN_OPT_EVENT_CHAR_06072022" MODIFY ("SRCH_CHAR_VAL" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."D1_DYN_OPT_EVENT_CHAR_06072022" MODIFY ("CHAR_VAL_FK5" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."D1_DYN_OPT_EVENT_CHAR_06072022" MODIFY ("CHAR_VAL_FK4" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."D1_DYN_OPT_EVENT_CHAR_06072022" MODIFY ("CHAR_VAL_FK3" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."D1_DYN_OPT_EVENT_CHAR_06072022" MODIFY ("CHAR_VAL_FK2" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."D1_DYN_OPT_EVENT_CHAR_06072022" MODIFY ("CHAR_VAL_FK1" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."D1_DYN_OPT_EVENT_CHAR_06072022" MODIFY ("ADHOC_CHAR_VAL" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."D1_DYN_OPT_EVENT_CHAR_06072022" MODIFY ("CHAR_VAL" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."D1_DYN_OPT_EVENT_CHAR_06072022" MODIFY ("SEQ_NUM" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."D1_DYN_OPT_EVENT_CHAR_06072022" MODIFY ("CHAR_TYPE_CD" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."D1_DYN_OPT_EVENT_CHAR_06072022" MODIFY ("DYN_OPT_EVENT_ID" NOT NULL ENABLE);
