--------------------------------------------------------
--  Constraints for Table D1_DYN_OPT_EVENT_LOG_06072022
--------------------------------------------------------

  ALTER TABLE "ASB_STG"."D1_DYN_OPT_EVENT_LOG_06072022" MODIFY ("BO_STATUS_REASON_CD" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."D1_DYN_OPT_EVENT_LOG_06072022" MODIFY ("VERSION" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."D1_DYN_OPT_EVENT_LOG_06072022" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."D1_DYN_OPT_EVENT_LOG_06072022" MODIFY ("CHAR_VAL_FK5" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."D1_DYN_OPT_EVENT_LOG_06072022" MODIFY ("CHAR_VAL_FK4" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."D1_DYN_OPT_EVENT_LOG_06072022" MODIFY ("CHAR_VAL_FK3" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."D1_DYN_OPT_EVENT_LOG_06072022" MODIFY ("CHAR_VAL_FK2" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."D1_DYN_OPT_EVENT_LOG_06072022" MODIFY ("CHAR_VAL_FK1" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."D1_DYN_OPT_EVENT_LOG_06072022" MODIFY ("ADHOC_CHAR_VAL" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."D1_DYN_OPT_EVENT_LOG_06072022" MODIFY ("CHAR_VAL" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."D1_DYN_OPT_EVENT_LOG_06072022" MODIFY ("CHAR_TYPE_CD" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."D1_DYN_OPT_EVENT_LOG_06072022" MODIFY ("MESSAGE_NBR" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."D1_DYN_OPT_EVENT_LOG_06072022" MODIFY ("MESSAGE_CAT_NBR" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."D1_DYN_OPT_EVENT_LOG_06072022" MODIFY ("BO_STATUS_CD" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."D1_DYN_OPT_EVENT_LOG_06072022" MODIFY ("DESCRLONG" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."D1_DYN_OPT_EVENT_LOG_06072022" MODIFY ("LOG_DTTM" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."D1_DYN_OPT_EVENT_LOG_06072022" MODIFY ("LOG_ENTRY_TYPE_FLG" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."D1_DYN_OPT_EVENT_LOG_06072022" MODIFY ("SEQNO" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."D1_DYN_OPT_EVENT_LOG_06072022" MODIFY ("DYN_OPT_EVENT_ID" NOT NULL ENABLE);
