--------------------------------------------------------
--  Constraints for Table D1_US_QTY_PROD
--------------------------------------------------------

  ALTER TABLE "ASB_STG"."D1_US_QTY_PROD" MODIFY ("VERSION" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."D1_US_QTY_PROD" MODIFY ("STATUS_UPD_DTTM" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."D1_US_QTY_PROD" MODIFY ("BO_STATUS_CD" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."D1_US_QTY_PROD" MODIFY ("US_QTY_USG_FLG" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."D1_US_QTY_PROD" MODIFY ("START_DTTM" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."D1_US_QTY_PROD" MODIFY ("D1_US_QTY_TYPE_CD" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."D1_US_QTY_PROD" MODIFY ("ID_VALUE" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."D1_US_QTY_PROD" MODIFY ("US_ID" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."D1_US_QTY_PROD" MODIFY ("D1_US_QTY_ID" NOT NULL ENABLE);
