--------------------------------------------------------
--  Constraints for Table D1_US_QTY_PROD2
--------------------------------------------------------

  ALTER TABLE "ASB_STG"."D1_US_QTY_PROD2" MODIFY ("VERSION" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."D1_US_QTY_PROD2" MODIFY ("STATUS_UPD_DTTM" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."D1_US_QTY_PROD2" MODIFY ("BO_STATUS_CD" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."D1_US_QTY_PROD2" MODIFY ("US_QTY_USG_FLG" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."D1_US_QTY_PROD2" MODIFY ("START_DTTM" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."D1_US_QTY_PROD2" MODIFY ("D1_US_QTY_TYPE_CD" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."D1_US_QTY_PROD2" MODIFY ("ID_VALUE" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."D1_US_QTY_PROD2" MODIFY ("US_ID" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."D1_US_QTY_PROD2" MODIFY ("D1_US_QTY_ID" NOT NULL ENABLE);
