--------------------------------------------------------
--  Constraints for Table F1_SVC_TASK_LOG_PARM_10OCT_BK
--------------------------------------------------------

  ALTER TABLE "ASB_STG"."F1_SVC_TASK_LOG_PARM_10OCT_BK" MODIFY ("VERSION" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."F1_SVC_TASK_LOG_PARM_10OCT_BK" MODIFY ("MSG_PARM_VAL" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."F1_SVC_TASK_LOG_PARM_10OCT_BK" MODIFY ("MSG_PARM_TYP_FLG" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."F1_SVC_TASK_LOG_PARM_10OCT_BK" MODIFY ("PARM_SEQ" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."F1_SVC_TASK_LOG_PARM_10OCT_BK" MODIFY ("SEQNO" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."F1_SVC_TASK_LOG_PARM_10OCT_BK" MODIFY ("F1_SVC_TASK_ID" NOT NULL ENABLE);
