--------------------------------------------------------
--  Constraints for Table F1_SVC_TASK_10OCT_BK
--------------------------------------------------------

  ALTER TABLE "ASB_STG"."F1_SVC_TASK_10OCT_BK" MODIFY ("VERSION" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."F1_SVC_TASK_10OCT_BK" MODIFY ("F1_STASK_TYPE_CD" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."F1_SVC_TASK_10OCT_BK" MODIFY ("BO_STATUS_CD" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."F1_SVC_TASK_10OCT_BK" MODIFY ("BUS_OBJ_CD" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."F1_SVC_TASK_10OCT_BK" MODIFY ("F1_SVC_TASK_ID" NOT NULL ENABLE);
