--------------------------------------------------------
--  Constraints for Table F1_SVC_TASK_LOG_10OCT_BK
--------------------------------------------------------

  ALTER TABLE "ASB_STG"."F1_SVC_TASK_LOG_10OCT_BK" MODIFY ("VERSION" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."F1_SVC_TASK_LOG_10OCT_BK" MODIFY ("SRCH_CHAR_VAL" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."F1_SVC_TASK_LOG_10OCT_BK" MODIFY ("CHAR_VAL_FK5" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."F1_SVC_TASK_LOG_10OCT_BK" MODIFY ("CHAR_VAL_FK4" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."F1_SVC_TASK_LOG_10OCT_BK" MODIFY ("CHAR_VAL_FK3" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."F1_SVC_TASK_LOG_10OCT_BK" MODIFY ("CHAR_VAL_FK2" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."F1_SVC_TASK_LOG_10OCT_BK" MODIFY ("CHAR_VAL_FK1" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."F1_SVC_TASK_LOG_10OCT_BK" MODIFY ("ADHOC_CHAR_VAL" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."F1_SVC_TASK_LOG_10OCT_BK" MODIFY ("CHAR_VAL" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."F1_SVC_TASK_LOG_10OCT_BK" MODIFY ("SEQ_NUM" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."F1_SVC_TASK_LOG_10OCT_BK" MODIFY ("CHAR_TYPE_CD" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."F1_SVC_TASK_LOG_10OCT_BK" MODIFY ("F1_SVC_TASK_ID" NOT NULL ENABLE);
