--------------------------------------------------------
--  Constraints for Table L_D1_INSTALL_EVT
--------------------------------------------------------

  ALTER TABLE "ASB_STG"."L_D1_INSTALL_EVT" MODIFY ("VERSION" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."L_D1_INSTALL_EVT" MODIFY ("CRE_DTTM" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."L_D1_INSTALL_EVT" MODIFY ("STATUS_UPD_DTTM" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."L_D1_INSTALL_EVT" MODIFY ("BO_STATUS_REASON_CD" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."L_D1_INSTALL_EVT" MODIFY ("BO_STATUS_CD" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."L_D1_INSTALL_EVT" MODIFY ("BUS_OBJ_CD" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."L_D1_INSTALL_EVT" MODIFY ("INSTALLATION_CONST" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."L_D1_INSTALL_EVT" MODIFY ("DEVICE_CONFIG_ID" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."L_D1_INSTALL_EVT" MODIFY ("D1_SP_ID" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."L_D1_INSTALL_EVT" MODIFY ("INSTALL_EVT_ID" NOT NULL ENABLE);
