--------------------------------------------------------
--  Constraints for Table L_D1_MEASR_COMP
--------------------------------------------------------

  ALTER TABLE "ASB_STG"."L_D1_MEASR_COMP" MODIFY ("D1_FULL_SCALE" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."L_D1_MEASR_COMP" MODIFY ("VERSION" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."L_D1_MEASR_COMP" MODIFY ("BO_STATUS_REASON_CD" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."L_D1_MEASR_COMP" MODIFY ("STATUS_UPD_DTTM" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."L_D1_MEASR_COMP" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."L_D1_MEASR_COMP" MODIFY ("D1_READ_SEQ" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."L_D1_MEASR_COMP" MODIFY ("TIME_ZONE_CD" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."L_D1_MEASR_COMP" MODIFY ("MEASR_COMP_MULTIPLIER" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."L_D1_MEASR_COMP" MODIFY ("D1_NBR_OF_DGTS_RGT" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."L_D1_MEASR_COMP" MODIFY ("D1_NBR_OF_DGTS_LFT" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."L_D1_MEASR_COMP" MODIFY ("MEASR_COMP_USAGE_FLG" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."L_D1_MEASR_COMP" MODIFY ("BO_STATUS_CD" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."L_D1_MEASR_COMP" MODIFY ("BUS_OBJ_CD" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."L_D1_MEASR_COMP" MODIFY ("MEASR_COMP_TYPE_CD" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."L_D1_MEASR_COMP" MODIFY ("DEVICE_CONFIG_ID" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."L_D1_MEASR_COMP" MODIFY ("MEASR_COMP_ID" NOT NULL ENABLE);
