--------------------------------------------------------
--  Constraints for Table MV_MEASR_COMP_ID_BK226
--------------------------------------------------------

  ALTER TABLE "ASB_STG"."MV_MEASR_COMP_ID_BK226" MODIFY ("MEASR_COMP_ID" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."MV_MEASR_COMP_ID_BK226" MODIFY ("MEASR_COMP_TYPE_CD" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."MV_MEASR_COMP_ID_BK226" MODIFY ("DEVICE_CONFIG_ID" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."MV_MEASR_COMP_ID_BK226" MODIFY ("SP_ID_TYPE_FLG" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."MV_MEASR_COMP_ID_BK226" MODIFY ("D1_SP_ID" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."MV_MEASR_COMP_ID_BK226" MODIFY ("ID_VALUE" NOT NULL ENABLE);
