--------------------------------------------------------
--  Constraints for Table PN_OPERATION_STG
--------------------------------------------------------

  ALTER TABLE "ASB_STG"."PN_OPERATION_STG" MODIFY ("ITEM_CODE" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."PN_OPERATION_STG" MODIFY ("FILE_DATE" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."PN_OPERATION_STG" MODIFY ("OP_LEVEL" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."PN_OPERATION_STG" MODIFY ("RANK" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."PN_OPERATION_STG" MODIFY ("EFFECTIVE" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."PN_OPERATION_STG" MODIFY ("ASB_UNIT_CODE" NOT NULL ENABLE);
