--------------------------------------------------------
--  Constraints for Table PN_OPERATION_STG2
--------------------------------------------------------

  ALTER TABLE "ASB_STG"."PN_OPERATION_STG2" MODIFY ("ITEM_CODE" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."PN_OPERATION_STG2" MODIFY ("FILE_DATE" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."PN_OPERATION_STG2" MODIFY ("OP_LEVEL" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."PN_OPERATION_STG2" MODIFY ("RANK" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."PN_OPERATION_STG2" MODIFY ("EFFECTIVE" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."PN_OPERATION_STG2" MODIFY ("ASB_UNIT_CODE" NOT NULL ENABLE);
