--------------------------------------------------------
--  Constraints for Table SRD_REDECLARATION_STG
--------------------------------------------------------

  ALTER TABLE "ASB_STG"."SRD_REDECLARATION_STG" MODIFY ("CONTRACT_SEQ" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."SRD_REDECLARATION_STG" MODIFY ("FILE_DATE" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."SRD_REDECLARATION_STG" MODIFY ("AVAIL_LEVEL" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."SRD_REDECLARATION_STG" MODIFY ("REDEC_ISSUE" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."SRD_REDECLARATION_STG" MODIFY ("REDEC_END" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."SRD_REDECLARATION_STG" MODIFY ("REDEC_START" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."SRD_REDECLARATION_STG" MODIFY ("CONTRACT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."SRD_REDECLARATION_STG" MODIFY ("ASB_UNIT_CODE" NOT NULL ENABLE);
