--------------------------------------------------------
--  Constraints for Table STGADM_D1_US_IDENTIFIER
--------------------------------------------------------

  ALTER TABLE "ASB_STG"."STGADM_D1_US_IDENTIFIER" MODIFY ("VERSION" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."STGADM_D1_US_IDENTIFIER" MODIFY ("ID_VALUE" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."STGADM_D1_US_IDENTIFIER" MODIFY ("US_ID_TYPE_FLG" NOT NULL ENABLE);
  ALTER TABLE "ASB_STG"."STGADM_D1_US_IDENTIFIER" MODIFY ("US_ID" NOT NULL ENABLE);
