--------------------------------------------------------
--  DDL for Table AKS_TEST
--------------------------------------------------------

  CREATE TABLE "ASB_STG"."AKS_TEST" 
   (	"TIME_PER" TIMESTAMP (6) DEFAULT systimestamp, 
	"TEXT_IDENTIFIER" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;