--------------------------------------------------------
--  DDL for Table ASB_RESOURCE_SELECTION_STG
--------------------------------------------------------

  CREATE TABLE "ASB_STG"."ASB_RESOURCE_SELECTION_STG" 
   (	"LOAD_SEQ_NBR" NUMBER(10,0), 
	"CONTRACT_SEQ" NUMBER(22,0), 
	"ASB_COMP_CODE" VARCHAR2(5 BYTE), 
	"ASB_STAT_CODE" VARCHAR2(10 BYTE), 
	"ASB_UNIT_CODE" VARCHAR2(10 BYTE), 
	"UNIT_TYPE" VARCHAR2(1 BYTE), 
	"DATE_CREATED" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 