--------------------------------------------------------
--  DDL for Table ASB_INDEX_RATE_STG
--------------------------------------------------------

  CREATE TABLE "ASB_STG"."ASB_INDEX_RATE_STG" 
   (	"LOAD_SEQ_NBR" NUMBER(10,0), 
	"ASB_PAYEE_CODE" VARCHAR2(5 BYTE), 
	"SERVICE_CODE" VARCHAR2(4 BYTE), 
	"EFFECTIVE" DATE, 
	"INDEX_CODE" VARCHAR2(4 BYTE), 
	"INDEX_RATE" NUMBER(12,6), 
	"FINANCIAL_YEAR" NUMBER(4,0), 
	"ASB_UNIT_CODE" VARCHAR2(10 BYTE), 
	"PAY_CODE" VARCHAR2(4 BYTE), 
	"DATE_CREATED" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 