--------------------------------------------------------
--  DDL for Table ASB_CONTRACT_SERVICE_NGPS
--------------------------------------------------------

  CREATE TABLE "ASB_STG"."ASB_CONTRACT_SERVICE_NGPS" 
   (	"LOAD_SEQ_NBR" NUMBER(10,0), 
	"CONTRACT_SEQ" NUMBER(22,0), 
	"ASB_COMP_CODE" VARCHAR2(5 BYTE), 
	"SERVICE_CODE" VARCHAR2(4 BYTE), 
	"CONTRACT_ID" VARCHAR2(20 BYTE), 
	"CONTRACT_STATUS" VARCHAR2(1 BYTE), 
	"CONTRACT_START" DATE, 
	"CONTRACT_END" DATE, 
	"TENDER_ID" VARCHAR2(20 BYTE), 
	"GROUP_ID" VARCHAR2(15 BYTE), 
	"DATE_CREATED" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  