--------------------------------------------------------
--  DDL for Table ASB_SEASON_STG
--------------------------------------------------------

  CREATE TABLE "ASB_STG"."ASB_SEASON_STG" 
   (	"LOAD_SEQ_NBR" VARCHAR2(10 BYTE), 
	"SEASON_SEQ" NUMBER(5,0), 
	"SERVICE_CODE" VARCHAR2(4 BYTE), 
	"EFFECTIVE" DATE, 
	"FINANCIAL_YEAR" NUMBER(4,0), 
	"SEASON_NUMBER" NUMBER(1,0), 
	"SUPPLEMENTARY" CHAR(1 BYTE), 
	"DATE_CREATED" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  