--------------------------------------------------------
--  DDL for Table ASB_UNIT_STG
--------------------------------------------------------

  CREATE TABLE "ASB_STG"."ASB_UNIT_STG" 
   (	"LOAD_SEQ_NBR" NUMBER(10,0), 
	"ASB_UNIT_CODE" VARCHAR2(10 BYTE), 
	"EFFECTIVE" DATE, 
	"GOAL_UNIT_CODE" VARCHAR2(9 BYTE), 
	"BM_UNIT_CODE" VARCHAR2(11 BYTE), 
	"REG_STATION_NAME" VARCHAR2(20 BYTE), 
	"DATE_CREATED" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 