--------------------------------------------------------
--  DDL for Table ASB_CPNY_STG
--------------------------------------------------------

  CREATE TABLE "ASB_STG"."ASB_CPNY_STG" 
   (	"LOAD_SEQ_NBR" NUMBER(10,0), 
	"ASB_COMP_CODE" VARCHAR2(5 BYTE), 
	"ASB_COMP_NAME" VARCHAR2(100 BYTE), 
	"REG_COMP_NAME" VARCHAR2(100 BYTE), 
	"DATE_CREATED" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
