--------------------------------------------------------
--  DDL for Table CCW_MISSING_RECORDS_17677
--------------------------------------------------------

  CREATE TABLE "ASB_STG"."CCW_MISSING_RECORDS_17677" 
   (	"DYN_OPT_ID" NUMBER, 
	"START_DTTM" DATE, 
	"END_DTTM" DATE, 
	"CREATED_DATE" DATE DEFAULT systimestamp
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 