--------------------------------------------------------
--  DDL for Table COMPANY_CSV_CUT3
--------------------------------------------------------

  CREATE TABLE "ASB_STG"."COMPANY_CSV_CUT3" 
   (	"ASB_COMP_CODE" VARCHAR2(5 BYTE), 
	"VENDOR_CODE" VARCHAR2(30 BYTE), 
	"VENDOR_CODE_EFFECTIVEDT" DATE, 
	"VAT_PERC" NUMBER(9,6), 
	"VAT_PERC_EFFECTIVEDT" DATE, 
	"VAT_CODE" VARCHAR2(30 BYTE), 
	"VAT_CODE_EFFECTIVEDT" DATE, 
	"INV_RECPT" VARCHAR2(100 BYTE), 
	"INV_ADD1" VARCHAR2(100 BYTE), 
	"INV_ADD2" VARCHAR2(100 BYTE), 
	"INV_ADD3" VARCHAR2(100 BYTE), 
	"INV_ADD4" VARCHAR2(100 BYTE), 
	"INV_ADD5" VARCHAR2(90 BYTE), 
	"POSTCODE" VARCHAR2(12 BYTE), 
	"EMAIL_RECPT_NAME" VARCHAR2(4000 BYTE), 
	"EMAIL_RECPT" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 