--------------------------------------------------------
--  DDL for Table CONNECT_US_SA_ID_NGPS
--------------------------------------------------------

  CREATE TABLE "ASB_STG"."CONNECT_US_SA_ID_NGPS" 
   (	"LOAD_SEQ_NBR" NUMBER(10,0), 
	"CONTRACT_SEQ" NUMBER(22,0), 
	"ASB_UNIT_CODE" VARCHAR2(10 BYTE), 
	"US_ID" CHAR(12 BYTE), 
	"SA_ID" CHAR(10 BYTE), 
	"DATE_CREATED" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 