--------------------------------------------------------
--  DDL for Table D1_DYN_OPT_EVENT_06072022
--------------------------------------------------------

  CREATE TABLE "ASB_STG"."D1_DYN_OPT_EVENT_06072022" 
   (	"DYN_OPT_EVENT_ID" CHAR(14 BYTE), 
	"BUS_OBJ_CD" CHAR(30 BYTE), 
	"BO_STATUS_CD" CHAR(12 BYTE), 
	"BO_STATUS_REASON_CD" VARCHAR2(30 BYTE), 
	"DYN_OPT_ID" CHAR(12 BYTE), 
	"START_DTTM" DATE, 
	"END_DTTM" DATE, 
	"STATUS_UPD_DTTM" DATE, 
	"CRE_DTTM" DATE, 
	"VERSION" NUMBER(5,0), 
	"BO_DATA_AREA" CLOB, 
	"QUANTITY" NUMBER(16,6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("BO_DATA_AREA") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
 