--------------------------------------------------------
--  DDL for Table D1_US_QTY_PROD
--------------------------------------------------------

  CREATE TABLE "ASB_STG"."D1_US_QTY_PROD" 
   (	"D1_US_QTY_ID" CHAR(12 BYTE), 
	"US_ID" CHAR(12 BYTE), 
	"ID_VALUE" VARCHAR2(120 BYTE), 
	"D1_US_QTY_TYPE_CD" VARCHAR2(30 BYTE), 
	"START_DTTM" DATE, 
	"END_DTTM" DATE, 
	"US_QTY_USG_FLG" CHAR(4 BYTE), 
	"BO_STATUS_CD" CHAR(12 BYTE), 
	"STATUS_UPD_DTTM" DATE, 
	"VERSION" DATE, 
	"D1_QUANTITY1" NUMBER(16,6), 
	"D1_QUANTITY2" NUMBER(16,6), 
	"D1_QUANTITY3" NUMBER(16,6), 
	"D1_QUANTITY4" NUMBER(16,6), 
	"D1_QUANTITY5" NUMBER(16,6), 
	"START_DT_NEW" DATE, 
	"END_DT_NEW" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 