--------------------------------------------------------
--  DDL for Table F1_SVC_TASK_10OCT_BK
--------------------------------------------------------

  CREATE TABLE "ASB_STG"."F1_SVC_TASK_10OCT_BK" 
   (	"F1_SVC_TASK_ID" CHAR(14 BYTE), 
	"BUS_OBJ_CD" CHAR(30 BYTE), 
	"BO_STATUS_CD" CHAR(12 BYTE), 
	"F1_STASK_TYPE_CD" VARCHAR2(30 BYTE), 
	"CRE_DTTM" DATE, 
	"STATUS_UPD_DTTM" DATE, 
	"EFF_DTTM" DATE, 
	"VERSION" NUMBER(5,0), 
	"BO_STATUS_REASON_CD" VARCHAR2(30 BYTE), 
	"ILM_DT" DATE, 
	"ILM_ARCH_SW" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
