--------------------------------------------------------
--  DDL for Table F1_SVC_TASK_LOG_PARM_10OCT_BK
--------------------------------------------------------

  CREATE TABLE "ASB_STG"."F1_SVC_TASK_LOG_PARM_10OCT_BK" 
   (	"F1_SVC_TASK_ID" CHAR(14 BYTE), 
	"SEQNO" NUMBER(5,0), 
	"PARM_SEQ" NUMBER(3,0), 
	"MSG_PARM_TYP_FLG" CHAR(4 BYTE), 
	"MSG_PARM_VAL" VARCHAR2(2000 BYTE), 
	"VERSION" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
