--------------------------------------------------------
--  DDL for Table FILE_DATA
--------------------------------------------------------

  CREATE TABLE "ASB_STG"."FILE_DATA" 
   (	"FILENAME" VARCHAR2(100 BYTE), 
	"DATETIME" DATE, 
	"TASK_ID" CHAR(14 BYTE), 
	"FILE_TYPE" VARCHAR2(25 BYTE), 
	"MSG_CLASS" VARCHAR2(50 BYTE), 
	"TRANS_BO" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 