--------------------------------------------------------
--  DDL for Table L_D1_INSTALL_EVT
--------------------------------------------------------

  CREATE TABLE "ASB_STG"."L_D1_INSTALL_EVT" 
   (	"INSTALL_EVT_ID" CHAR(12 BYTE), 
	"D1_SP_ID" CHAR(12 BYTE), 
	"DEVICE_CONFIG_ID" CHAR(12 BYTE), 
	"D1_INSTALL_DTTM" DATE, 
	"D1_REMOVAL_DTTM" DATE, 
	"INSTALLATION_CONST" NUMBER(12,6), 
	"BUS_OBJ_CD" CHAR(30 BYTE), 
	"BO_STATUS_CD" CHAR(12 BYTE), 
	"BO_STATUS_REASON_CD" VARCHAR2(30 BYTE), 
	"STATUS_UPD_DTTM" DATE, 
	"CRE_DTTM" DATE, 
	"VERSION" NUMBER(5,0), 
	"ARM_STAT_FLG" CHAR(4 BYTE), 
	"BO_DATA_AREA" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("BO_DATA_AREA") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
 