--------------------------------------------------------
--  DDL for Table LOAD_DETAILS
--------------------------------------------------------

  CREATE TABLE "ASB_STG"."LOAD_DETAILS" 
   (	"LOAD_SEQ_NBR" NUMBER(10,0), 
	"LOAD_DESC" VARCHAR2(100 BYTE), 
	"REC_PROCESSED" NUMBER(10,0), 
	"REC_REJECTED" NUMBER(10,0), 
	"DATE_CREATED" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 