--------------------------------------------------------
--  DDL for Table OWNER_CSV
--------------------------------------------------------

  CREATE TABLE "ASB_STG"."OWNER_CSV" 
   (	"LOAD_SEQ_NBR" NUMBER(10,0), 
	"RESOURCE_CODE" VARCHAR2(10 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"COMPANY_CODE" VARCHAR2(10 BYTE), 
	"OWNED_EFF_START_DT" DATE, 
	"OWNED_EFF_END_DT" DATE, 
	"PAYMENT_EFF_START_DT" DATE, 
	"PAYMENT_EFF_END_DT" DATE, 
	"ERROR_CODE" NUMBER(3,0), 
	"DATE_CREATED" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  