--------------------------------------------------------
--  DDL for Table PN_RANGE_STG
--------------------------------------------------------

  CREATE TABLE "ASB_STG"."PN_RANGE_STG" 
   (	"LOAD_SEQ_NBR" NUMBER(10,0), 
	"ASB_UNIT_CODE" VARCHAR2(10 BYTE), 
	"ITEM_CODE" VARCHAR2(4 BYTE), 
	"EFFECTIVE" DATE, 
	"RATE_1" NUMBER(6,3), 
	"ELBOW_2" NUMBER(10,3), 
	"RATE_2" NUMBER(6,3), 
	"ELBOW_3" NUMBER(10,3), 
	"RATE_3" NUMBER(6,3), 
	"FILE_DATE" DATE, 
	"DATE_CREATED" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 