--------------------------------------------------------
--  DDL for Table PROCESS_LOG
--------------------------------------------------------

  CREATE TABLE "ASB_STG"."PROCESS_LOG" 
   (	"PROC_SEQ_NBR" NUMBER(10,0), 
	"PROC_NAME" VARCHAR2(100 BYTE), 
	"LOAD_SEQ_NBR" NUMBER(10,0), 
	"STATUS" VARCHAR2(10 BYTE), 
	"STATUS_DESCRIPTION" VARCHAR2(4000 BYTE), 
	"DATE_CREATED" DATE, 
	"ENTITY_NAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 