--------------------------------------------------------
--  DDL for Table RESOURCE_CSV_BKP_2
--------------------------------------------------------

  CREATE TABLE "ASB_STG"."RESOURCE_CSV_BKP_2" 
   (	"LOAD_SEQ_NBR" NUMBER(10,0), 
	"ASB_UNIT_CODE" VARCHAR2(10 BYTE), 
	"RESOURCE_TYPE" VARCHAR2(5 BYTE), 
	"RESOURCE_TYP_EFFDT" DATE, 
	"SPL_RESOURCE_TYPE" VARCHAR2(25 BYTE), 
	"SPL_RES_TYP_EFFDT" DATE, 
	"BM_STATION_NAME" VARCHAR2(20 BYTE), 
	"BM_STAT_NAME_EFFDT" DATE, 
	"METER_TYPE" VARCHAR2(5 BYTE), 
	"METER_TYPE_EFFDT" DATE, 
	"NBMTOBM_MAP" VARCHAR2(15 BYTE), 
	"NBMTOBM_MAP_EFFDT" DATE, 
	"SERVICE_PROVISION" VARCHAR2(50 BYTE), 
	"SERVICE_PROVISION_EFFDT" DATE, 
	"MAX_MW" NUMBER(6,0), 
	"MAX_MW_EFFDT" DATE, 
	"ERROR_CODE" NUMBER(3,0), 
	"DATE_CREATED" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 