--------------------------------------------------------
--  DDL for Table SP_BMU_STG
--------------------------------------------------------

  CREATE TABLE "ASB_STG"."SP_BMU_STG" 
   (	"LOAD_SEQ_NBR" NUMBER(10,0), 
	"ASB_UNIT_CODE" VARCHAR2(10 BYTE), 
	"SETT_DATE" DATE, 
	"SETT_PER" NUMBER(2,0), 
	"FPN_VOLUME" NUMBER(10,3), 
	"BO_VOLUME" NUMBER(10,3), 
	"EXPECTED_VOLUME" NUMBER(10,3), 
	"METERED_VOLUME" NUMBER(10,3), 
	"IMBALANCE_VOLUME" NUMBER(10,3), 
	"TLM_SCALAR" NUMBER(8,7), 
	"ND_CHARGE" NUMBER(10,2), 
	"SETT_GMT_TIME" DATE, 
	"SETT_BST_TIME" DATE, 
	"DATE_CREATED" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 