--------------------------------------------------------
--  DDL for Table SRD_INSTRUCTION_STG
--------------------------------------------------------

  CREATE TABLE "ASB_STG"."SRD_INSTRUCTION_STG" 
   (	"LOAD_SEQ_NBR" NUMBER(10,0), 
	"ASB_UNIT_CODE" VARCHAR2(10 BYTE), 
	"CONTRACT_NUMBER" NUMBER(4,2), 
	"INSR_START" DATE, 
	"INSR_END" DATE, 
	"INSR_ISSUE" DATE, 
	"OP_LEVEL" NUMBER(10,3), 
	"STATUS" NUMBER(1,0), 
	"FILE_DATE" DATE, 
	"CONTRACT_SEQ" NUMBER(22,0), 
	"DATE_CREATED" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 