--------------------------------------------------------
--  DDL for Table SRS_CONTRACT_FACTOR_STG
--------------------------------------------------------

  CREATE TABLE "ASB_STG"."SRS_CONTRACT_FACTOR_STG" 
   (	"LOAD_SEQ_NBR" NUMBER(10,0), 
	"CONTRACT_SEQ" NUMBER(22,0), 
	"EFFECTIVE" DATE, 
	"STANDBY_TOLERANCE" NUMBER(2,0), 
	"DELIVERY_TOLERANCE" NUMBER(2,0), 
	"AVAIL_REDUCTION" NUMBER(2,0), 
	"DATE_CREATED" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 