--------------------------------------------------------
--  DDL for Table SRS_FAILURE_PALL_EOD
--------------------------------------------------------

  CREATE TABLE "ASB_STG"."SRS_FAILURE_PALL_EOD" 
   (	"CONTRACT_SEQ" NUMBER(22,0), 
	"CONTRACT_NUMBER" NUMBER(4,2), 
	"FAIL_CODE" VARCHAR2(4 BYTE), 
	"FAIL_ENTRY" CHAR(1 BYTE), 
	"FAIL_SUPP" NUMBER(1,0), 
	"CONTRACT_START" DATE, 
	"CONTRACT_END" DATE, 
	"FAIL_START_LOC" DATE, 
	"FAIL_END_LOC" DATE, 
	"FAIL_START_2" DATE, 
	"FAIL_END_2" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 