--------------------------------------------------------
--  DDL for Table SRS_DESPATCH_STG
--------------------------------------------------------

  CREATE TABLE "ASB_STG"."SRS_DESPATCH_STG" 
   (	"LOAD_SEQ_NBR" NUMBER(10,0), 
	"CONTRACT_SEQ" NUMBER(22,0), 
	"EFFECTIVE" DATE, 
	"SRD_INSTALLED" CHAR(1 BYTE), 
	"SRD_SITE" VARCHAR2(4 BYTE), 
	"SRD_LOAD" VARCHAR2(20 BYTE), 
	"SRD_AGENT" VARCHAR2(4 BYTE), 
	"SRD_HQ" VARCHAR2(4 BYTE), 
	"SRD_CALLOFF" VARCHAR2(4 BYTE), 
	"INSR_MECH" VARCHAR2(3 BYTE), 
	"TEL_NUMBER" VARCHAR2(61 BYTE), 
	"FAX_NUMBER" VARCHAR2(67 BYTE), 
	"DATE_CREATED" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 