--------------------------------------------------------
--  DDL for Table SRS_SUPPLIER_STG
--------------------------------------------------------

  CREATE TABLE "ASB_STG"."SRS_SUPPLIER_STG" 
   (	"LOAD_SEQ_NBR" NUMBER(10,0), 
	"CONTRACT_SEQ" NUMBER(22,0), 
	"ASB_UNIT_CODE" VARCHAR2(10 BYTE), 
	"TENDER_NUMBER" NUMBER(4,2), 
	"CONTRACT_NUMBER" NUMBER(4,2), 
	"CONT_CAPACITY" NUMBER(3,0), 
	"OPTN_CAPACITY" NUMBER(3,0), 
	"MAX_UTILISATION" NUMBER(4,1), 
	"RESPONSE_TIME" NUMBER(5,0), 
	"RECOVERY_PERIOD" NUMBER(4,0), 
	"MNZT_LIMIT" NUMBER(4,0), 
	"EXP_CAPACITY" NUMBER(3,0), 
	"IMP_CAPACITY" NUMBER(3,0), 
	"CEASE_TIME" NUMBER(3,0), 
	"RAMPUP_RATE" NUMBER(5,2), 
	"RAMPDOWN_RATE" NUMBER(5,2), 
	"DEFAULT_SUPPLIER" CHAR(1 BYTE), 
	"INCLUDE_CONTRACT" CHAR(1 BYTE), 
	"SPINGEN_ADJUST" NUMBER(5,2), 
	"DUMMY_CONTRACT" CHAR(1 BYTE), 
	"DATE_CREATED" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 