--------------------------------------------------------
--  DDL for Table SRS_CONTRACT_FORM_STG
--------------------------------------------------------

  CREATE TABLE "ASB_STG"."SRS_CONTRACT_FORM_STG" 
   (	"LOAD_SEQ_NBR" VARCHAR2(10 BYTE), 
	"CONTRACT_SEQ" NUMBER(22,0), 
	"COMM_FLEX" VARCHAR2(1 BYTE), 
	"NORTH_SOUTH" VARCHAR2(1 BYTE), 
	"MAX_OCCS_WEEK" NUMBER(2,0), 
	"MAX_HOURS_WEEK" NUMBER(4,1), 
	"MAX_OCCS_CONT" NUMBER(4,0), 
	"MAX_HOURS_CONT" NUMBER(4,0), 
	"NEAREST_NODE" VARCHAR2(6 BYTE), 
	"LOCATION" VARCHAR2(65 BYTE), 
	"SUPPLEMENTARY" VARCHAR2(1 BYTE), 
	"PROVIDER_TYPE" VARCHAR2(3 BYTE), 
	"DATE_CREATED" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 