--------------------------------------------------------
--  DDL for Table SRS_ACPT_PENALTY_STG
--------------------------------------------------------

  CREATE TABLE "ASB_STG"."SRS_ACPT_PENALTY_STG" 
   (	"LOAD_SEQ_NBR" NUMBER(10,0), 
	"EFFECTIVE_DATE" DATE, 
	"ACCEPTED_PENALTY_DURATION" NUMBER(4,2), 
	"DATE_CREATED" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 