--------------------------------------------------------
--  DDL for Table SRS_HEADROOM_METER_STG
--------------------------------------------------------

  CREATE TABLE "ASB_STG"."SRS_HEADROOM_METER_STG" 
   (	"LOAD_SEQ_NBR" NUMBER(10,0), 
	"ASB_UNIT_CODE" VARCHAR2(10 BYTE), 
	"EFFECTIVE_FROM" DATE, 
	"EFFECTIVE_TO" DATE, 
	"AVAIL_METER" VARCHAR2(15 BYTE), 
	"AVAIL_HEADROOM" VARCHAR2(1 BYTE), 
	"UTIL_METER" VARCHAR2(15 BYTE), 
	"UTIL_HEADROOM" VARCHAR2(1 BYTE), 
	"DATE_CREATED" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 