--------------------------------------------------------
--  DDL for Table SRS_MONITORING_STG_DUMMY
--------------------------------------------------------

  CREATE TABLE "ASB_STG"."SRS_MONITORING_STG_DUMMY" 
   (	"ASB_UNIT_CODE" VARCHAR2(10 BYTE), 
	"METER_DELAY" NUMBER(2,0), 
	"EFFECTIVE" DATE, 
	"EFFECTIVE_END" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 