--------------------------------------------------------
--  DDL for Table SRS_SECTION_PAYMENT_STG
--------------------------------------------------------

  CREATE TABLE "ASB_STG"."SRS_SECTION_PAYMENT_STG" 
   (	"LOAD_SEQ_NBR" NUMBER(10,0), 
	"RESOURCE_CODE" VARCHAR2(10 BYTE), 
	"PAY_CODE" VARCHAR2(4 BYTE), 
	"PAY_START" DATE, 
	"PAY_END" DATE, 
	"CONTRACT_SEQ" NUMBER(22,0), 
	"PAY_DATE" DATE, 
	"PRICE_BASE" NUMBER(12,6), 
	"PAY_RATE" NUMBER(12,6), 
	"PAY_VALUE" NUMBER(12,2), 
	"DURATION" NUMBER(4,0), 
	"CONTRACT_NUMBER" NUMBER(4,2), 
	"FINANCIAL_YEAR" NUMBER(4,0), 
	"SEASON_NUMBER" NUMBER(1,0), 
	"DAY_CODE" VARCHAR2(4 BYTE), 
	"SERVICE_PERIOD" NUMBER(1,0), 
	"AVAIL_FLAG" CHAR(1 BYTE), 
	"FM_STATUS" NUMBER(1,0), 
	"FF_STATUS" NUMBER(1,0), 
	"MAN_FAIL" CHAR(1 BYTE), 
	"AUTO_FAIL" CHAR(1 BYTE), 
	"AVAIL_LEV" NUMBER(10,3), 
	"NUM_BO_PAIR" NUMBER(2,0), 
	"BID_PRICE" NUMBER(10,5), 
	"OFFER_PRICE" NUMBER(10,5), 
	"BO_LEVEL" NUMBER(10,3), 
	"FPN_VOLUME" NUMBER(10,3), 
	"NDZ" NUMBER(4,0), 
	"MDP" NUMBER(4,0), 
	"MZT" NUMBER(4,0), 
	"UTIL_ISSUED" DATE, 
	"UTIL_LEVEL" NUMBER(10,3), 
	"UTIL_PAY_RATE" NUMBER(12,6), 
	"MNZT" NUMBER(4,0), 
	"EXPECTED_VOLUME" NUMBER(10,3), 
	"METERED_VOLUME" NUMBER(10,3), 
	"BO_VOLUME" NUMBER(10,3), 
	"CAPBL_FAIL" CHAR(1 BYTE), 
	"UTIL_FAIL" CHAR(1 BYTE), 
	"CONTRACTED_ENERGY" NUMBER(10,3), 
	"EXPECTED_ENERGY" NUMBER(10,3), 
	"METERED_ENERGY" NUMBER(10,3), 
	"DELIVERED_ENERGY" NUMBER(10,3), 
	"CAPPED_ENERGY" NUMBER(10,3), 
	"RESPONSE_FAIL" VARCHAR2(4 BYTE), 
	"DELIVERY_FAIL" VARCHAR2(4 BYTE), 
	"OTHER_FAIL" VARCHAR2(4 BYTE), 
	"RAMP_FLAG" CHAR(1 BYTE), 
	"DATE_CREATED" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 