--------------------------------------------------------
--  DDL for Table STGADM_D1_US_IDENTIFIER
--------------------------------------------------------

  CREATE TABLE "ASB_STG"."STGADM_D1_US_IDENTIFIER" 
   (	"US_ID" CHAR(12 BYTE), 
	"US_ID_TYPE_FLG" CHAR(4 BYTE), 
	"ID_VALUE" VARCHAR2(120 BYTE), 
	"VERSION" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 