--------------------------------------------------------
--  DDL for Table STOR_ACCEPTED_TEND_QES
--------------------------------------------------------

  CREATE TABLE "ASB_STG"."STOR_ACCEPTED_TEND_QES" 
   (	"CONTRACT_NUMBER" NUMBER(4,2), 
	"NGESO_UNIT_ID" VARCHAR2(10 BYTE), 
	"WINDOW_START_DATE_TIME" DATE, 
	"WINDOW_END_DATE_TIME" DATE, 
	"AVAILABILITY_PRICE" NUMBER(12,6), 
	"CONTRACTED_MW" NUMBER(3,0), 
	"SERVICE_TYPE" VARCHAR2(8 BYTE), 
	"DATE_CREATED" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
