--------------------------------------------------------
--  DDL for Package PKG_BM_PROFILE
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE "ASB_STG"."PKG_BM_PROFILE" AS 

  PROCEDURE PR_BM_PROFILE_MAIN(p_VERSION IN NUMBER);
  PROCEDURE PR_LOAD_ASBSTG_BM_PROFILE(p_START_DATE DATE, p_END_DATE DATE, p_RANK NUMBER, p_load_seq_nbr IN number,p_VERSION IN NUMBER);
  PROCEDURE PR_MSM1_BM_PROFILE(p_LOAD_SEQ_NBR IN NUMBER,p_VERSION IN NUMBER,p_RANK NUMBER,p_START_DATE DATE,p_END_DATE DATE);
  PROCEDURE PR_MSM2_BM_PROFILE(p_LOAD_SEQ_NBR IN NUMBER,p_VERSION IN NUMBER);
  PROCEDURE PR_CISADM_BM_PROFILE(p_LOAD_SEQ_NBR IN NUMBER,p_VERSION IN NUMBER);

END PKG_BM_PROFILE;

/

